<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.example</groupId>
    <artifactId>order-parent</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>
    <modules>
        <module>order-adapter</module>
        <module>order-start</module>
        <module>order-client</module>
        <module>order-app</module>
        <module>order-domain</module>
        <module>order-infrastructure</module>
    </modules>
</project>
