-- 订单信息表
CREATE TABLE t_order_info (
    id              bigint(20)     NOT NULL COMMENT '主键id',
    order_no        varchar(36)    NOT NULL COMMENT '订单编号',
    creator_id      varchar(36)    NOT NULL COMMENT '创建人id',
    create_time     datetime       NOT NULL COMMENT '创建时间',
    last_updater_id varchar(36)    NOT NULL COMMENT '最后更新人id',
    last_update_time datetime      NOT NULL COMMENT '最后更新时间',
    del_flag        tinyint(4)     NOT NULL DEFAULT 0 COMMENT '删除标志[0-否,1-是]',
    order_status    varchar(10)    NOT NULL COMMENT '订单状态',
    f01            varchar(20)    NOT NULL COMMENT '字段01',
    f02            varchar(20)    NOT NULL COMMENT '字段02',
    f03            varchar(20)    NOT NULL COMMENT '字段03',
    f04            varchar(20)    NOT NULL COMMENT '字段04',
    f05            varchar(20)    NOT NULL COMMENT '字段05',
    f06            varchar(20)    NOT NULL COMMENT '字段06',
    f07            varchar(20)    NOT NULL COMMENT '字段07',
    f08            varchar(20)    NOT NULL COMMENT '字段08',
    f09            varchar(20)    NOT NULL COMMENT '字段09',
    f10            varchar(20)    NOT NULL COMMENT '字段10',
    f11            varchar(20)    NOT NULL COMMENT '字段11',
    f12            varchar(20)    NOT NULL COMMENT '字段12',
    f13            varchar(20)    NOT NULL COMMENT '字段13',
    f14            varchar(20)    NOT NULL COMMENT '字段14',
    f15            varchar(20)    NOT NULL COMMENT '字段15',
    f16            varchar(20)    NOT NULL COMMENT '字段16',
    f17            varchar(20)    NOT NULL COMMENT '字段17',
    f18            varchar(20)    NOT NULL COMMENT '字段18',
    f19            varchar(20)    NOT NULL COMMENT '字段19',
    f20            varchar(20)    NOT NULL COMMENT '字段20',
    f21            varchar(20)    NOT NULL COMMENT '字段21',
    f22            varchar(20)    NOT NULL COMMENT '字段22',
    f23            varchar(20)    NOT NULL COMMENT '字段23',
    f24            varchar(20)    NOT NULL COMMENT '字段24',
    f25            varchar(20)    NOT NULL COMMENT '字段25',
    f26            varchar(20)    NOT NULL COMMENT '字段26',
    f27            varchar(20)    NOT NULL COMMENT '字段27',
    f28            varchar(20)    NOT NULL COMMENT '字段28',
    f29            varchar(20)    NOT NULL COMMENT '字段29',
    f30            varchar(20)    NOT NULL COMMENT '字段30',
    f31            varchar(20)    NOT NULL COMMENT '字段31',
    f32            varchar(20)    NOT NULL COMMENT '字段32',
    f33            varchar(20)    NOT NULL COMMENT '字段33',
    PRIMARY KEY (id),
    UNIQUE KEY uk_order_no (order_no),
    KEY ix_order_status (order_status)
) COMMENT = '订单信息表';
